### ISSUE TITLE
Shaders causing screen aberrations. 

### ISSUE THREAD

**Issue by echo451** [grondag/json-model-extensions#5]
The original bug was reported here

https://github.com/Shnupbups/extra-pieces/issues/6#issuecomment-508894496

The author indicated that the problem was likely with JMX, They ask that I post a report here. 

The specifics are that a change in the version of extra-pieces resulted in the problem.

To see what the effect are reference back to the original bug report. 

For more information let me know if there is anything that I can add to help resolve this problem. 

The details here are sparse but more complete in the original report.

**Comment by grondag** [comment]
This is a general problem with any model that uses the Fabric Renderer API.  It's not JMX-specific.  JMX triggers it because it converts some vanilla models to use the API.

However, I'm leaving this open as a tracking defect until the Fabric API can be adjusted to prevent the problem or it is definitely determined it won't be.

**Comment by grondag** [comment]
Should be resolved via the latest release of Indigo. See https://github.com/FabricMC/fabric/pull/295
